version: '3.1'

services:
  concert-app:
    container_name: concert-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3123:3000"  # Mapea el puerto 3000 del contenedor al puerto 3123 del host
    environment:
      - NODE_ENV=prodcuction  # Establece el entorno a desarroll
      - USER_EMAIL_SENDER=zetita159@gmail.com
      - PASS_EMAIL_SENDER=itfh nxuc fcos jmgi
      - URL_APP_SCRIPT_GET=https://script.google.com/macros/s/AKfycbx1GecgRStxWzmHOnUY_z9KGuHuQPZPqbJQ8l7IMAqBT_IJg1KUrr73vsLHtdk22lWEcw/exec
      - URL_APP_SCRIPT_UPDATE=https://script.google.com/macros/s/AKfycbwYAYtDLKblWyFS3f3TI487s34F2W9ICzLgXmr5q8BeUo1WdF7nYXyI-YCXVyE-LUdniQ/exec
      
    volumes:
      - .:/usr/src/app  # Monta el directorio actual en el contenedor
